@baseURL=http://localhost:5000

@JWTToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNTU3NjZlOTQ4ZGE1NGQ5NDFlMmI1MCIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzg0MTEyMTMwLCJleHAiOjE3ODQxMTkzMzB9.qzDY65zwJ97bThxB8SPIhr_JvlkWLegcQ4PhyaT_auc
###
POST {{baseURL}}/api/auth/login 
Authorization: Bearer {{JWTToken}}
Content-Type: application/json

{
    "username": "manager2",
    "password": "newpassword111"
}

###
GET {{baseURL}}/api/menu-categories
Authorization: Bearer {{JWTToken}}

###
GET {{baseURL}}/api/menu-categories/search?query=drink
Authorization: Bearer {{JWTToken}}

###
GET {{baseURL}}/api/menu-categories/6a12f1c8398d135b84143a1d
Authorization: Bearer {{JWTToken}}

###
POST {{baseURL}}/api/menu-categories
Authorization: Bearer {{JWTToken}}
Content-Type: application/json

{
    "name": "Loose Changes"
}

###
PUT {{baseURL}}/api/menu-categories/6a21738267ae271b2a0b54bd
Authorization: Bearer {{JWTToken}}
Content-Type: application/json

{
    "name": "Penny Pinchers"
}

###
DELETE {{baseURL}}/api/menu-categories/6a21738267ae271b2a0b54bd
Authorization: Bearer {{JWTToken}}
