@baseURL=http://localhost:5000

###
POST {{baseURL}}/api/auth/login 
Content-Type: application/json

{
    "username": "manager2",
    "password": "newpassword111"
}

###
GET {{baseURL}}/api/menu
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMjExYmRmYzg3MDY2ZTNlMzgxNGNmZSIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzgwNTc2MjkzLCJleHAiOjE3ODA1ODM0OTN9.clG9GjpD8YlXFMdTeVSBKwwPXZRkVtisGYInOLBkPZ8

###
GET {{baseURL}}/api/menu/6a1c0790da31bdb4401c3678
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMjExYmRmYzg3MDY2ZTNlMzgxNGNmZSIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzgwNTc1ODgwLCJleHAiOjE3ODA1ODMwODB9.r9EOM_6I3bqTI1j_z4INhveE1bhnG8098PGcJ669_Xk
###
GET {{baseURL}}/api/menu/search?ques=Steak
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMjExYmRmYzg3MDY2ZTNlMzgxNGNmZSIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzgwNTc1ODgwLCJleHAiOjE3ODA1ODMwODB9.r9EOM_6I3bqTI1j_z4INhveE1bhnG8098PGcJ669_Xk
###
POST {{baseURL}}/api/menu
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMjExYmRmYzg3MDY2ZTNlMzgxNGNmZSIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzgwNTc1ODgwLCJleHAiOjE3ODA1ODMwODB9.r9EOM_6I3bqTI1j_z4INhveE1bhnG8098PGcJ669_Xk
Content-Type: application/json

{
  "name": "English Breakfast Tea",
  "description": "A robust blend of black teas from Assam and Ceylon, perfect for a morning pick-me-up.",
  "category": "6a12f1c8398d135b84143a1c",
  "price": 3.5,
  "photo": null,
  "dietaryFlags": [
    "vegan",
    "vegetarian",
    "glutenFree",
    "nutFree"
  ],
  "Availability": true
}

###
PUT {{baseURL}}/api/menu/6a217147f62fec2944456b7a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMjExYmRmYzg3MDY2ZTNlMzgxNGNmZSIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzgwNTc1ODgwLCJleHAiOjE3ODA1ODMwODB9.r9EOM_6I3bqTI1j_z4INhveE1bhnG8098PGcJ669_Xk
Content-Type: application/json

{
    "name": "Earl Grey Tea",
    "description": "A robust blend of black teas from Assam and Ceylon, perfect for a morning pick-me-up.",
    "category":"6a12f1c8398d135b84143a1c",
    "price": 3.5,
    "photo": null,
    "dietaryFlags": [
        "vegan",
        "vegetarian",
        "glutenFree"
    ],
    "Availability": false
}

###
PATCH {{baseURL}}/api/menu/6a217147f62fec2944456b7a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMjExYmRmYzg3MDY2ZTNlMzgxNGNmZSIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzgwNTc1ODgwLCJleHAiOjE3ODA1ODMwODB9.r9EOM_6I3bqTI1j_z4INhveE1bhnG8098PGcJ669_Xk
Content-Type: application/json

{
    "price": 4.0,
    "Availability": true
}

###
DELETE {{baseURL}}/api/menu/6a217147f62fec2944456b7a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMjExYmRmYzg3MDY2ZTNlMzgxNGNmZSIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzgwNTc1ODgwLCJleHAiOjE3ODA1ODMwODB9.r9EOM_6I3bqTI1j_z4INhveE1bhnG8098PGcJ669_Xk