@baseURL=http://localhost:5000
@JWTToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNTU3NjZlOTQ4ZGE1NGQ5NDFlMmI1MCIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzg0MTEyMTMwLCJleHAiOjE3ODQxMTkzMzB9.qzDY65zwJ97bThxB8SPIhr_JvlkWLegcQ4PhyaT_auc
###
POST {{baseURL}}/api/auth/login 
Content-Type: application/json

{
    "username": "manager1",
    "password": "password123"
}

###
GET {{baseURL}}/api/menu-items
Authorization: Bearer {{JWTToken}}

###
GET {{baseURL}}/api/menu-items/6a1c0790da31bdb4401c3678
Authorization: Bearer {{JWTToken}}
###
GET {{baseURL}}/api/menu-items/search?query=Steak
Authorization: Bearer {{JWTToken}}
###
POST {{baseURL}}/api/menu-items
Authorization: Bearer {{JWTToken}}
Content-Type: application/json

{
  "name": "English Breakfast Tea",
  "description": "A robust blend of black teas from Assam and Ceylon, perfect for a morning pick-me-up.",
  "category": "6a12f1c8398d135b84143a1c",
  "price": 3.5,
  "photo": null,
  "dietaryFlags": [
    "vegan",
    "vegetarian",
    "glutenFree",
    "nutFree"
  ],
  "Availability": true
}

###
PUT {{baseURL}}/api/menu-items/6a55746dc9f93617cf229d07
Authorization: Bearer {{JWTToken}}
Content-Type: application/json

{
    "name": "Mocha Latte",
    "description": "A robust blend of black teas from Assam and Ceylon, perfect for a morning pick-me-up.",
    "category":"6a12f1c8398d135b84143a1c",
    "price": 3.5,
    "photo": null,
    "dietaryFlags": [
        "vegan",
        "vegetarian",
        "glutenFree"
    ],
    "Availability": false
}

###
PATCH {{baseURL}}/api/menu-items/6a55746dc9f93617cf229d07
Authorization: Bearer {{JWTToken}}
Content-Type: application/json

{
    "price": 4.0,
    "Availability": true
}

###
DELETE {{baseURL}}/api/menu-items/6a55746dc9f93617cf229d07
Authorization: Bearer {{JWTToken}}