@baseURL=http://localhost:5000

###
POST {{baseURL}}/api/auth/login 
Content-Type: application/json

{
    "username": "manager1",
    "password": "password123"
}

###
GET {{baseURL}}/api/menu-items
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNTI0ZDYxOTEzNTk4OGI0MzJkNGY0NSIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzgzODM1MDY4LCJleHAiOjE3ODM4NDIyNjh9.WIH7sCLwR1kcsC0F2V6kKlkt_G-go901gqbEhHZxTZk

###
GET {{baseURL}}/api/menu/6a1c0790da31bdb4401c3678
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMjExYmRmYzg3MDY2ZTNlMzgxNGNmZSIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzgwNTc1ODgwLCJleHAiOjE3ODA1ODMwODB9.r9EOM_6I3bqTI1j_z4INhveE1bhnG8098PGcJ669_Xk
###
GET {{baseURL}}/api/menu-items/search?query=Steak
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNTI0ZDYxOTEzNTk4OGI0MzJkNGY0NSIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzgzODM1MDY4LCJleHAiOjE3ODM4NDIyNjh9.WIH7sCLwR1kcsC0F2V6kKlkt_G-go901gqbEhHZxTZk
###
POST {{baseURL}}/api/menu
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMjExYmRmYzg3MDY2ZTNlMzgxNGNmZSIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzgxNDgzMzczLCJleHAiOjE3ODE0OTA1NzN9.brNKwQn2pEHphetppcxws4WE26K7mSZJCKy7ZmHOjXM
Content-Type: application/json

{
  "name": "English Breakfast Tea",
  "description": "A robust blend of black teas from Assam and Ceylon, perfect for a morning pick-me-up.",
  "category": "6a12f1c8398d135b84143a1c",
  "price": 3.5,
  "photo": null,
  "dietaryFlags": [
    "vegan",
    "vegetarian",
    "glutenFree",
    "nutFree"
  ],
  "Availability": true
}

###
PUT {{baseURL}}/api/menu/6a21701bbc2eeb8b8547bcef
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMjExYmRmYzg3MDY2ZTNlMzgxNGNmZSIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzgxMjMwNjEzLCJleHAiOjE3ODEyMzc4MTN9.hSxhi_DR7u6fx2o7YnIEMq1DWEui4o6jfPMrsMmG854
Content-Type: application/json

{
    "name": "Mocha Latte",
    "description": "A robust blend of black teas from Assam and Ceylon, perfect for a morning pick-me-up.",
    "category":"6a12f1c8398d135b84143a1c",
    "price": 3.5,
    "photo": null,
    "dietaryFlags": [
        "vegan",
        "vegetarian",
        "glutenFree"
    ],
    "Availability": false
}

###
PATCH {{baseURL}}/api/menu/6a21701bbc2eeb8b8547bcef
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMjExYmRmYzg3MDY2ZTNlMzgxNGNmZSIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzgxMjMwMzY3LCJleHAiOjE3ODEyMzc1Njd9.M1enaiRoI0yQao2Kp_yQJFat6cMsTYuACIJGkPcFQC4
Content-Type: application/json

{
    "price": 4.0,
    "Availability": true
}

###
DELETE {{baseURL}}/api/menu/6a21701bbc2eeb8b8547bcef
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMjExYmRmYzg3MDY2ZTNlMzgxNGNmZSIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzgxMjMwMzY3LCJleHAiOjE3ODEyMzc1Njd9.M1enaiRoI0yQao2Kp_yQJFat6cMsTYuACIJGkPcFQC4