@baseURL=http://localhost:5000


@JWTToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNTU3NjZlOTQ4ZGE1NGQ5NDFlMmI1MCIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzg0MTEyMTMwLCJleHAiOjE3ODQxMTkzMzB9.qzDY65zwJ97bThxB8SPIhr_JvlkWLegcQ4PhyaT_auc
###
POST {{baseURL}}/api/auth/login 
Content-Type: application/json

{
    "username": "manager2",
    "password": "newpassword111"
}

###
GET {{baseURL}}/api/orders
Authorization: Bearer {{JWTToken}}

###
GET {{baseURL}}/api/orders/6a0b02bae9bcca1c0c3030f0
Authorization: Bearer {{JWTToken}}
###
GET {{baseURL}}/api/orders/search?query=O1
Authorization: Bearer {{JWTToken}}

###
POST {{baseURL}}/api/orders
Authorization: Bearer {{JWTToken}}
Content-Type: application/json

{
    "tableCode": "O1",
    "dateTime": "2024-05-15T12:30:00Z",
    "status": "in-progress",
    "menuItems": [
        {
            "menuItemId": "6a0af065f4d4ac42863330e5",
            "quantity": 2
        },
        {
            "menuItemId": "6a0aedfadb631e57ad5c3327",
            "quantity": 1
        }
    ]
}

###
PUT {{baseURL}}/api/orders/6a216dcf958f5a558fa5a6ec
Authorization: Bearer {{JWTToken}}
Content-Type: application/json

{
    "tableCode": "B5",
    "dateTime": "2024-05-15T12:30:00Z",
    "status": "completed",
    "menuItems": [
        {
            "menuItemId": "6a0af065f4d4ac42863330e5",
            "quantity": 2
        },
        {
            "menuItemId": "6a0aedfadb631e57ad5c3327",
            "quantity": 1
        }
    ]
}

###
PATCH {{baseURL}}/api/orders/6a216dcf958f5a558fa5a6ec
Authorization: Bearer {{JWTToken}}
Content-Type: application/json

{
    "status": "completed"
}

###
DELETE {{baseURL}}/api/orders/6a216dcf958f5a558fa5a6ec
Authorization: Bearer {{JWTToken}}