@baseURL=http://localhost:5000


###
POST {{baseURL}}/api/auth/login 
Content-Type: application/json

{
    "username": "manager2",
    "password": "newpassword111"
}

###
GET {{baseURL}}/api/order
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMjExYmRmYzg3MDY2ZTNlMzgxNGNmZSIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzgwNTc1NTA4LCJleHAiOjE3ODA1ODI3MDh9.ubZ6g3z4g643qdZp7n6Vvc8qo2BU5YFL2xVl1x6DYb8

###
GET {{baseURL}}/api/order/6a0b02bae9bcca1c0c3030f0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMjExYmRmYzg3MDY2ZTNlMzgxNGNmZSIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzgwNTc1NTA4LCJleHAiOjE3ODA1ODI3MDh9.ubZ6g3z4g643qdZp7n6Vvc8qo2BU5YFL2xVl1x6DYb8
###
GET {{baseURL}}/api/order/search?ques=O1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMjExYmRmYzg3MDY2ZTNlMzgxNGNmZSIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzgwNTc1NTA4LCJleHAiOjE3ODA1ODI3MDh9.ubZ6g3z4g643qdZp7n6Vvc8qo2BU5YFL2xVl1x6DYb8

###
POST {{baseURL}}/api/order
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMjExYmRmYzg3MDY2ZTNlMzgxNGNmZSIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzgwNTc1NTA4LCJleHAiOjE3ODA1ODI3MDh9.ubZ6g3z4g643qdZp7n6Vvc8qo2BU5YFL2xVl1x6DYb8
Content-Type: application/json

{
    "tableCode": "O1",
    "dateTime": "2024-05-15T12:30:00Z",
    "status": "in-progress",
    "menuItems": [
        {
            "menuItemId": "6a0af065f4d4ac42863330e5",
            "quantity": 2
        },
        {
            "menuItemId": "6a0aedfadb631e57ad5c3327",
            "quantity": 1
        }
    ]
}

###
PUT {{baseURL}}/api/order/6a216dcf958f5a558fa5a6ec
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMjExYmRmYzg3MDY2ZTNlMzgxNGNmZSIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzgwNTc1NTA4LCJleHAiOjE3ODA1ODI3MDh9.ubZ6g3z4g643qdZp7n6Vvc8qo2BU5YFL2xVl1x6DYb8
Content-Type: application/json

{
    "tableCode": "B5",
    "dateTime": "2024-05-15T12:30:00Z",
    "status": "completed",
    "menuItems": [
        {
            "menuItemId": "6a0af065f4d4ac42863330e5",
            "quantity": 2
        },
        {
            "menuItemId": "6a0aedfadb631e57ad5c3327",
            "quantity": 1
        }
    ]
}

###
PATCH {{baseURL}}/api/order/6a216dcf958f5a558fa5a6ec
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMjExYmRmYzg3MDY2ZTNlMzgxNGNmZSIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzgwNTc1NTA4LCJleHAiOjE3ODA1ODI3MDh9.ubZ6g3z4g643qdZp7n6Vvc8qo2BU5YFL2xVl1x6DYb8
Content-Type: application/json

{
    "status": "completed"
}

###
DELETE {{baseURL}}/api/order/6a216dcf958f5a558fa5a6ec
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMjExYmRmYzg3MDY2ZTNlMzgxNGNmZSIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzgwNTc1NTA4LCJleHAiOjE3ODA1ODI3MDh9.ubZ6g3z4g643qdZp7n6Vvc8qo2BU5YFL2xVl1x6DYb8