@baseURL = http://localhost:5000

@JWTToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNTU3NjZlOTQ4ZGE1NGQ5NDFlMmI1MCIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzg0MTEyMTMwLCJleHAiOjE3ODQxMTkzMzB9.qzDY65zwJ97bThxB8SPIhr_JvlkWLegcQ4PhyaT_auc
###
POST {{baseURL}}/api/auth/login 
Content-Type: application/json

{
    "username": "manager2",
    "password": "newpassword111"
}

###
GET {{baseURL}}/api/tables
Authorization: Bearer {{JWTToken}}

###
GET {{baseURL}}/api/tables/6a0d90be43b0c375c754c7d8
Authorization: Bearer {{JWTToken}}

###
GET {{baseURL}}/api/tables/search?query=M1
Authorization: Bearer {{JWTToken}}

###
POST {{baseURL}}/api/tables
Authorization: Bearer {{JWTToken}}
Content-Type: application/json

{
    "area": "main",
    "tableCode": "M12"
}

###

PUT {{baseURL}}/api/tables/6a216bb56caca4b08f11ac92
Authorization: Bearer {{JWTToken}}
Content-Type: application/json

{
    "area": "main",
    "tableCode": "O12"
}

###

DELETE {{baseURL}}/api/tables/6a216bb56caca4b08f11ac92
Authorization: Bearer {{JWTToken}}
