@baseURL = http://localhost:5000

###
POST {{baseURL}}/api/auth/login 
Content-Type: application/json

{
    "username": "manager2",
    "password": "newpassword111"
}

###
GET {{baseURL}}/api/table
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMjExYmRmYzg3MDY2ZTNlMzgxNGNmZSIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzgwNTc1MTA0LCJleHAiOjE3ODA1ODIzMDR9.TYDMctbQhtOrcLkgjjLbJs-TEQrR9s2csVGjuvCw8xM

###
GET {{baseURL}}/api/table/6a0d90be43b0c375c754c7d8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMjExYmRmYzg3MDY2ZTNlMzgxNGNmZSIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzgwNTc1MTA0LCJleHAiOjE3ODA1ODIzMDR9.TYDMctbQhtOrcLkgjjLbJs-TEQrR9s2csVGjuvCw8xM

###
GET {{baseURL}}/api/table/search?ques=M1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMjExYmRmYzg3MDY2ZTNlMzgxNGNmZSIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzgwNTc1MTA0LCJleHAiOjE3ODA1ODIzMDR9.TYDMctbQhtOrcLkgjjLbJs-TEQrR9s2csVGjuvCw8xM

###
POST {{baseURL}}/api/table
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMjExYmRmYzg3MDY2ZTNlMzgxNGNmZSIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzgwNTc1MTA0LCJleHAiOjE3ODA1ODIzMDR9.TYDMctbQhtOrcLkgjjLbJs-TEQrR9s2csVGjuvCw8xM
Content-Type: application/json

{
    "area": "main",
    "tableCode": "M12"
}

###

PUT {{baseURL}}/api/table/6a216bb56caca4b08f11ac92
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMjExYmRmYzg3MDY2ZTNlMzgxNGNmZSIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzgwNTc1MTA0LCJleHAiOjE3ODA1ODIzMDR9.TYDMctbQhtOrcLkgjjLbJs-TEQrR9s2csVGjuvCw8xM
Content-Type: application/json

{
    "area": "main",
    "tableCode": "O12"
}

###

DELETE {{baseURL}}/api/table/6a216bb56caca4b08f11ac92
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMjExYmRmYzg3MDY2ZTNlMzgxNGNmZSIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzgwNTc1MTA0LCJleHAiOjE3ODA1ODIzMDR9.TYDMctbQhtOrcLkgjjLbJs-TEQrR9s2csVGjuvCw8xM
