@baseURL = http://localhost:5000

###

GET {{baseURL}}/api/users

###
GET {{baseURL}}/api/users/6a0d921f1f7c246a8b66025b

###
GET {{baseURL}}/api/users/search?ques=manager12

###
POST {{baseURL}}/api/users
Content-Type: application/json

{
    "username": "staff4",
    "password": "password999",
    "role": "staff"
}

###
PUT {{baseURL}}/api/users/6a0d921f1f7c246a8b66025c
Content-Type: application/json

{
    "username": "manager2",
    "password": "password111",
    "role": "manager"
}

###

PATCH {{baseURL}}/api/users/6a0d973d8cd419fabff51f51
Content-Type: application/json

{
    "password": "newpassword123",
    "role": "staff"
}

###
DELETE {{baseURL}}/api/users/6a0d921f1f7c246a8b66025c

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "staff4",
    "password": "password999"
}

###
GET http://localhost:5000/api/menu/

###
DELETE http://localhost:5000/api/menu/6a05640f2e567066acfea409
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMDU2NDBmMmU1NjcwNjZhY2ZlYTQwNiIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzc4NzM4NDM5LCJleHAiOjE3Nzg3NDU2Mzl9.vklqEUbWuUXAo1R_5vQ0Q3AMjV89tEa9_8KkGGstRDs