@baseURL = http://localhost:5000
@JWTToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNTU3NjZlOTQ4ZGE1NGQ5NDFlMmI1MCIsInJvbGUiOiJtYW5hZ2VyIiwiaWF0IjoxNzg0MTEyMTMwLCJleHAiOjE3ODQxMTkzMzB9.qzDY65zwJ97bThxB8SPIhr_JvlkWLegcQ4PhyaT_auc
### login
POST {{baseURL}}/api/auth/login 
Content-Type: application/json

{
    "username": "manager1",
    "password": "password123"
}

###
GET {{baseURL}}/api/users
Authorization: Bearer {{JWTToken}}

###
GET {{baseURL}}/api/users/6a211bc077a2c3ed429ac666
Authorization: Bearer {{JWTToken}}
###
GET {{baseURL}}/api/users/search?query=manager2
Authorization: Bearer {{JWTToken}}
###
POST {{baseURL}}/api/users
Authorization: Bearer {{JWTToken}}
Content-Type: application/json

{
    "username": "manager3",
    "password": "newpassword111",
    "role": "manager"
}

###
PUT {{baseURL}}/api/users/6a0d921f1f7c246a8b66025c
Authorization: Bearer {{JWTToken}}
Content-Type: application/json

{
    "username": "manager2",
    "password": "password111",
    "role": "manager"
}

###

PATCH {{baseURL}}/api/users/6a21154ebb5286100e9b43f1
Authorization: Bearer {{JWTToken}}
Content-Type: application/json

{
    "password": "newpassword123"
}

###
DELETE {{baseURL}}/api/users/6a0d921f1f7c246a8b66025c
Authorization: Bearer {{JWTToken}}

###

GET  {{baseURL}}/api/auth

###
# POST {{baseURL}}/api/auth/logout
# Content-Type: application/json

# {
#     "username": "manager2",
#     "password": "newpassword123"
# }

POST {{baseURL}}/api/auth/logout
Authorization: Bearer {{JWTToken}}

###
GET {{baseURL}}/api/menu-items/

### 
### "No quotations from bearer to end of token string.""
DELETE {{baseURL}}/api/menu-items/6a1c0790da31bdb4401c3679
Authorization: Bearer {{JWTToken}}